# Generated by Django 3.2.4 on 2023-09-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynews',
            old_name='news_discription',
            new_name='news_description',
        ),
    ]
